matrix:
  include:
    - os: linux
      services: docker
      language: generic

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

script:
  - |
      docker build -t publisher:v1 . && \
      docker docker container run --detach --name publisher publisher:v1 \
      docker exec publisher:v1 npm run release

before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"