matrix:
  include:
    - os: linux
      services: docker
      language: generic

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

install:
  - docker build -t publisher:v1 .
  - docker run -d --name publisher publisher:v1

script:
  - |
      docker exec publisher npm run release

deploy:
  provider: script
  script: docker build -t publisher:v1 . && docker run -d --name publisher publisher:v1 && docker exec publisher:v1 npm run release
  on:
    branch: master

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"