os: linux
language: node_js
node_js:
  - 10.15

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

before_install:
  - sudo dpkg --add-architecture i386
  - deb http://httpredir.debian.org/debian jessie-backports main && sudo apt-get update
  
install:
  - sudo apt install \
    wine/jessie-backports \
    wine32/jessie-backports \
    wine64/jessie-backports \
    libwine/jessie-backports \
    libwine:i386/jessie-backports \
    fonts-wine/jessie-backports
  - npm install

script:
  - npm run lint
  - npm run test
  - npm run release

deploy:
  provider: script
  script: npm run release
  on:
    branch: master
