matrix:
  include:
    - os: linux
      language: javascript

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

install:
  - npm install

script:
  - npm run lint
  - npm run test
  - npm run release

deploy:
  provider: script
  script: npm run release
  on:
    branch: master
