const fieldLabels = {
  childData: "Dane dziecka",
  "child.name": "Imię i nazwisko",
  "child.nameGenetiv": "Imię i nazwisko (dopełniacz)",
  childBirthplace: "Miejsce urodzenia",
  childPesel: "PESEL",
  childHome: "Miejsce zamieszkania",
  childPostalCode: "Kod pocztowy",
  childHomeStreet: "Ulica",
  childHomeNumber: "Numer lokalu/mieszkania",
  childSchoolType: "Rodzaj szkoły",
  childProfession: "Zawód",
  childClass: "Klasa",
  childSchoolName: "Szkoła",
  fatherFullName: "Imię i nazwisko ojca",
  motherFullName: "Imię i nazwisko matki",
  parentsHome: "Miejsce zamieszkania rodziców",
  "applicant.name": "wnioskodawcy (mianownik)",
  "applicant.nameGenetive": "wnioskodawcy (dopełniacz)",
  "applicant.address": "adres (ulica i numer, ew miejscowosc)",
  "applicant.postalCode": "kod pocztowy i miasto",
  typeOfApplication: "wniosek o",
  firstReason: "z uwagi (pierwsze)",
  secondReason: "z uwagi (drugie)",
  period: "na okres",
  "supportCenter.name": "Nazwa poradni",
  "supportCenter.address": "Adres poradni",
  "supportCenter.post": "Kod pocztowy poradni"
};

export default fieldLabels;
